wp-content/mu-plugins/pantheon/pantheon-cache.php
Other environments, including `test` and `dev`, are fine to use 0 second
ttls.
Also makes the behavior more consistent: if the ttl value is less than
60 seconds, then it should be forced to 60 seconds, not 600.
See #17 
Conversation in #34
=> Only force 60 second ttl in `live` environment (release-4.4)

.gitignore
It's intended for environment-specific project details
=> Ignore `wp-cli.local.yml` (release-4.4)

wp-config.php
This will automagically disable UI like the code editor and "Add
(Plugin|Theme)" experiences.
=> Let WordPress know FS writes are disabled in test and live

wp-content/mu-plugins/pantheon.php, wp-content/mu-plugins/pantheon/pantheon-cache-cli.php
```
salty-wordpress ➜  pantheon.dev  wp pantheon cache clear
Error: Please provide one or more URL paths to purge, or use the --all
flag.
```
```
salty-wordpress ➜  pantheon.dev  wp pantheon cache clear /foo/ /bar/
Success: Cache purged for 2 URL paths.
```
```
salty-wordpress ➜  pantheon.dev  wp pantheon cache clear --all
Success: Cache purged for all URL paths.
```
Fixes #27
=> Register `wp pantheon cache clear` for purging cache based on path

.gitignore
The Updraft and BackUpWordpress plugins are likely to generate very large binary objects inside the git-backed code directory of a website. These large objects should not be stored in git and will cause problems with workflows. This change will help keep these large files out of the git history.
=> Ignore directories likely to contain large binary objects

wp-includes/class-phpmailer.php, wp-includes/class-smtp.php
Update PHPMailer to version 5.2.19. For more information, see https://www.wordfence.com/blog/2016/12/phpmailer-vulnerability/.
=> WordPress 4.7-p1 [Security PATCH release]

wp-includes/class-phpmailer.php, wp-includes/class-smtp.php
Update PHPMailer to version 5.2.21. For more information, see https://www.wordfence.com/blog/2016/12/phpmailer-vulnerability/.
=> WordPress 4.7-p2 [Security PATCH release]. 

wp-content/mu-plugins/pantheon/pantheon-updates.php
Fixes #135
See original conversion in #136 and discovery with tests in https://github.com/wp-cli/wp-cli/pull/4395
=> Strip '-src' from `$wp_version` for more accurate version comparison

.circleci/.gitignore, .circleci/behat.yml, .circleci/cleanup.sh, .circleci/config.yml, .circleci/confirm-safety.sh, .circleci/features/0-install.feature, .circleci/features/bootstrap/AdminLogIn.php, .circleci/features/bootstrap/ResponseHeader.php, .circleci/features/comments.feature, .circleci/features/options.feature, .circleci/features/pantheon-logged-out.feature, .circleci/features/pantheon.feature, .circleci/features/plugins.feature, .circleci/features/posts.feature, .circleci/features/terms.feature, .circleci/features/themes.feature, .circleci/features/users.feature, .circleci/local.test.dist, .circleci/prepare.sh, .circleci/set-up-globals.sh, .circleci/test.sh
See [ENG-192](https://getpantheon.atlassian.net/browse/ENG-192) for plan.
This implementation forgoes the `test` branch and instead keeps the Circle tests exclusively on the `default` branch. Once this PR is merged, the `default` branch will be set as the default branch for this repo. Any PRs opened against this repo should be made against the default branch (which will be the default behavior if using the GitHub ui).  Note that the [downstream updater script to update WordPress](https://github.com/pantheon-systems/downstream-updater/blob/master/scripts/wp-update-site#L208:L212) now also bases the new WordPress versions off of the default branch.
=> Circle 2 test scripts

wp-content/mu-plugins/pantheon/pantheon-updates.php
Originally #140
In a local environment, the standard WordPress update nag will show if there's a WordPress update available.
In Pantheon environments, the standard WordPress update nag is removed. The Pantheon update nag will only appear if `pantheon_curl()` is available and returns `is_up_to_date_with_upstream=false`.
However, because we don't have the "version" of the upstream, I've made the message more generic:
=> Smarter WordPress Dashboard Custom Upstream Update Notifications

wp-content/mu-plugins/pantheon/pantheon-page-cache.php
Use `cache-control: no-cache, no-store, must-revalidate` when on the WordPress admin and logged-in
=> Remove `max-age` from logged-in responses

pantheon.upstream.yml
Enforce HTTPS by default. For more info see https://pantheon.io/blog/pantheon-now-enforces-https-default-plus-really-simple-hsts
=> [CORE-1353] Enforce HTTPS by default.

wp-admin/about.php, wp-includes/class-wp-query.php, wp-includes/class-wp.php, wp-includes/functions.php, wp-includes/http.php, wp-includes/pluggable.php, wp-includes/rest-api.php, wp-includes/script-loader.php, wp-includes/version.php
Update from WordPress 5.2.3 to WordPress 5.2.4.
- git fetch wp
- git merge wp/update-5.2.4
=> Update to WordPress 5.2.4. For more information, see https://wordpress.org/news/2019/10/wordpress-5-2-4-security-release/

wp-content/mu-plugins/pantheon/pantheon-updates.php
A fresh copy of @ataylorme's PR #217, as the original branch is stuck in limbo returning 404 & has merge conflict in .circleci/.
---
Partially addresses #216
- Do not show an update notice when using the default upstream and WordPress core is up to date
- Only show the upstream update notice on dev
- https://api.live.getpantheon.com/sites/self/code-upstream-updates does not return multidev information, so displaying an accurate notice on those environments is not feasible.
- Only disable WordPress auto updates when on Pantheon
=> [BUGS-2808] Update notification improvements

wp-config.php
fixes #160 
Historical context: https://make.wordpress.org/core/2015/04/02/the-utf8mb4-upgrade/
WordPress core has been setting this as the default for new sites for 3+ years (assuming the DB supports the feature)
https://github.com/WordPress/WordPress/blame/26bda18a23174afb048afbe62296c76a62add542/wp-admin/setup-config.php#L377
this setting is supported by all the MariaDb versions that I can find.
=> [OTTO-360] change default wp-config from utf8 to utf8mb4

wp-content/mu-plugins/pantheon/assets/css/return-to-pantheon-button.css, wp-content/mu-plugins/pantheon/pantheon-login-form-mods.php
To customize the explanatory text displayed on the Login screen, add the following filter to your theme's `functions.php` file or a mu-plugin:
```php
add_filter( 'pantheon_wp_login_text', function() {
return 'This is my custom and really long login message';
});
```
From #193
Fixes #192
=> Introduce a new filter to allow the Pantheon WordPress login text modified

pantheon.upstream.yml
The WordPress 5.4.2 release included an additional change to the way Pantheon manages protected web paths by adding the list explicitly to the pantheon.upstream.yml file. The paths listed in the new location were missing the trailing '/' character, which changed the behavior of the path matching. This amended release restores the missing trailing slashes. No changes to WordPress itself are included.
=> Amended WordPress 5.4.2 release.

.gitignore, wp-config-pantheon.php, wp-config.php
WordPress 5.5 introduces `wp_get_environment_type()`, which returns a site's environment type as defined by the constant `WP_ENVIRONMENT_TYPE`. 
The `live` environment returns `production`, `test` returns `staging`, and all other environments (`dev`, all multidevs) return `development`.
References:
https://make.wordpress.org/core/2020/07/24/new-wp_get_environment_type-function-in-wordpress-5-5/
=> [OTTO-395] set WP_ENVIRONMENT_TYPE according to Pantheon environment

wp-config-pantheon.php, wp-config.php
Per https://core.trac.wordpress.org/changeset/29630
This constant was deprecated in WordPress some time ago and should be removed from wp-config altogether since it is no longer used. The database instead provides this option.
Also clarifies language around keys & salts in `wp-config-pantheon.php`
Closes #83
Closes #252
=> [OTTO-406] wp-config.php: removed deprecated WPLANG, refactored "if" logic/syntax

wp-content/mu-plugins/pantheon/pantheon-page-cache.php
Updates Page Cache screen admin notices to link to Advanced Page Cache plugin's docs page instead of a possibly confusing plugin install search.
Minor coding standards updates for escaping content etc.
Fixes #114
=> Update page cache notices to link to caching docs page

wp-content/mu-plugins/pantheon/pantheon-updates.php
In addition to #263 & #264, further resolves issues with requests `api.live.getpantheon.com`.
`pantheon_curl_timeout` adds a default timeout of 1 second.
=> [BUGS-3668] Use pantheon_curl_timeout instead of pantheon_curl

wp-admin/about.php, wp-includes/functions.php, wp-includes/version.php
Update from WordPress 5.5.2 to WordPress 5.5.3.
- git fetch wp
- git merge wp/update-5.5.3
=> Update to WordPress 5.5.3. For more information, see https://wordpress.org/news/2020/10/wordpress-5-5-3-maintenance-release/

wp-admin/about.php, wp-includes/PHPMailer/PHPMailer.php, wp-includes/PHPMailer/SMTP.php, wp-includes/version.php
Update from WordPress 5.7.1 to WordPress 5.7.2.
- git fetch wp
- git merge wp/update-5.7.2
=> Update to WordPress 5.7.2. For more information, see https://wordpress.org/news/2021/05/wordpress-5-7-2-security-release/

wp-content/mu-plugins/pantheon/pantheon-updates.php
As noted in https://github.com/pantheon-systems/WordPress/issues/274, some of the .update-nag formatting went missing a while back, which makes the nag formatting appear somewhat inconsistent with other WordPress notices.
This commit restores the formatting that makes the nag look like other warning notices, using standard WordPress CSS class names.
=> Trigger CircleCI for PR #287

wp-admin/about.php, wp-admin/includes/upgrade.php, wp-includes/class-wp-meta-query.php, wp-includes/class-wp-tax-query.php, wp-includes/formatting.php, wp-includes/post.php, wp-includes/version.php
Update from WordPress 5.8.2 to WordPress 5.8.3.
- git fetch wp
- git merge wp/update-5.8.3
=> Update to WordPress 5.8.3. For more information, see https://wordpress.org/news/2022/01/wordpress-5-8-3-security-release/

wp-admin/about.php, wp-includes/block-template.php, wp-includes/blocks/template-part.php, wp-includes/version.php
Update from WordPress 6.2.1 to WordPress 6.2.2.
- git fetch wp
- git merge wp/update-6.2.2
=> Update to WordPress 6.2.2. For more information, see https://wordpress.org/news/2023/05/wordpress-6-2-2-security-release/

wp-config-pantheon.php
This PR adds a `PANTHEON_HOSTNAME` constant which defaults to `$_SERVER['HTTP_HOST']` if it exists.
When used to define `DOMAIN_CURRENT_SITE` on WordPress multisites (e.g. `define( 'DOMAIN_CURRENT_SITE', PANTHEON_HOSTNAME )`), this solves the "undefined index HTTP_HOST" error that shows up in PHP error logs.
=> [BUGS-7678] define PANTHEON_HOSTNAME constant

wp-admin/about.php, wp-admin/includes/plugin-install.php, wp-includes/blocks.php, wp-includes/blocks/template-part.php, wp-includes/fonts.php, wp-includes/formatting.php, wp-includes/functions.php, wp-includes/html-api/class-wp-html-tag-processor.php, wp-includes/rest-api/endpoints/class-wp-rest-font-faces-controller.php, wp-includes/version.php
Update from WordPress 6.5.4 to WordPress 6.5.5.
- git fetch wp
- git merge wp/update-6.5.5
=> Update to WordPress 6.5.5. For more information, see https://wordpress.org/news/2024/06/wordpress-6-5-5/
